const DATA_TYPE = {
  SHARED: "SHARED",
  UNIQUE: "UNIQUE",
};
exports.DATA_TYPE = DATA_TYPE;

const PAGE_CATEGORIES = {
  DRAFT: "DRAFT",
  FEATURED_NAV: "FEATURED_NAV",
  HIDDEN: "HIDDEN",
  HOME: "HOME",
  MAIN_NAV: "MAIN_NAVIGATION",
};
exports.PAGE_CATEGORIES = PAGE_CATEGORIES;

const PAGE_TYPES = {
  ITEM: "ITEM",
};
exports.PAGE_TYPES = PAGE_TYPES;

const BLOCK_CATEGORIES = {
  EXTRA: "EXTRA",
  FOOTER: "FOOTER",
  HERO: "HERO",
  MAIN: "MAIN",
};
exports.BLOCK_CATEGORIES = BLOCK_CATEGORIES;

const BLOCK_TYPES = {
  BASIC_TEXT: "BASIC_TEXT",
  BULLET_COLUMNS: "BULLET_COLUMNS",
  DATA_DETAILS: "DATA_DETAILS",
  DONATE: "DONATE",
  ENDORSEMENTS: "ENDORSEMENTS",
  EVENTS_LIST: "EVENTS_LIST",
  EVENTS_PAGE: "EVENTS_PAGE",
  FOOTER: "FOOTER",
  FULL_WIDTH_IMAGE: "FULL_WIDTH_IMAGE",
  FULL_WIDTH_VIDEO: "FULL_WIDTH_VIDEO",
  HERO: "HERO",
  INTRO: "INTRO",
  ISSUES_LIST: "ISSUES_LIST",
  ISSUES_PAGE: "ISSUES_PAGE",
  ISSUES: "ISSUES",
  LANDING_POPUP: "LANDING_POPUP",
  LIFE_DETAILS: "LIFE_DETAILS",
  LONG_FORM: "LONG_FORM",
  NEWS_LIST: "NEWS_LIST",
  NEWS_PAGE: "NEWS_PAGE",
  QUOTE_IMAGE: "QUOTE_IMAGE",
  QUOTE: "QUOTE",
  SHORT_FORM: "SHORT_FORM",
  TEXT_IMAGE: "TEXT_IMAGE",
  TEXT_WITH_SIDEBAR: "TEXT_WITH_SIDEBAR",
  TEXT: "TEXT",
  TIMELINE: "TIMELINE",
  TWITTER: "TWITTER",
};
exports.BLOCK_TYPES = BLOCK_TYPES;

const BLOCK_VARIANT = {
  CALLOUT: "CALLOUT",
  CUSTOM: "CUSTOM",
  DEFAULT: "DEFAULT",
  EXTRA: "EXTRA",
  LOCKED: "LOCKED",
  MULTI: "MULTI",
};
exports.BLOCK_VARIANT = BLOCK_VARIANT;

const INTRO_LAYOUT_TYPE = {
  SINGLE: "SINGLE",
  TWO: "TWO",
  VIDEO: "VIDEO",
};
exports.INTRO_LAYOUT_TYPE = INTRO_LAYOUT_TYPE;

const LANDING_POPUP_TYPES = {
  GENERAL: "GENERAL",
  DONATE: "DONATE",
  SIGNUP: "SIGNUP",
};
exports.LANDING_POPUP_TYPES = LANDING_POPUP_TYPES;
