export const DATA_TYPE = {
  SHARED: "SHARED",
  UNIQUE: "UNIQUE",
};

export const PAGE_CATEGORIES = {
  DRAFT: "DRAFT",
  FEATURED_NAV: "FEATURED_NAV",
  HIDDEN: "HIDDEN",
  HOME: "HOME",
  MAIN_NAV: "MAIN_NAVIGATION",
};

export const PAGE_TYPES = {
  ITEM: "ITEM",
};

export const BLOCK_CATEGORIES = {
  EXTRA: "EXTRA",
  FOOTER: "FOOTER",
  HERO: "HERO",
  MAIN: "MAIN",
  POPUP: "POPUP",
};

export const BLOCK_TYPES = {
  BASIC_TEXT: "BASIC_TEXT",
  BULLET_COLUMNS: "BULLET_COLUMNS",
  DATA_DETAILS: "DATA_DETAILS",
  DONATE: "DONATE",
  ENDORSEMENTS: "ENDORSEMENTS",
  EVENTS_LIST: "EVENTS_LIST",
  EVENTS_PAGE: "EVENTS_PAGE",
  FOOTER: "FOOTER",
  FULL_WIDTH_IMAGE: "FULL_WIDTH_IMAGE",
  FULL_WIDTH_VIDEO: "FULL_WIDTH_VIDEO",
  HERO: "HERO",
  INTRO: "INTRO",
  ISSUES_LIST: "ISSUES_LIST",
  ISSUES_PAGE: "ISSUES_PAGE",
  ISSUES: "ISSUES",
  LANDING_POPUP: "LANDING_POPUP",
  LIFE_DETAILS: "LIFE_DETAILS",
  LONG_FORM: "LONG_FORM",
  NEWS_LIST: "NEWS_LIST",
  NEWS_PAGE: "NEWS_PAGE",
  QUOTE_IMAGE: "QUOTE_IMAGE",
  QUOTE: "QUOTE",
  SHORT_FORM: "SHORT_FORM",
  TEXT_IMAGE: "TEXT_IMAGE",
  TEXT_WITH_SIDEBAR: "TEXT_WITH_SIDEBAR",
  TEXT: "TEXT",
  TIMELINE: "TIMELINE",
  TWITTER: "TWITTER",
};

export const BLOCK_VARIANT = {
  CALLOUT: "CALLOUT",
  CUSTOM: "CUSTOM",
  DEFAULT: "DEFAULT",
  EXTRA: "EXTRA",
  LOCKED: "LOCKED",
  MULTI: "MULTI",
};

export const BLOCK_FREQUENCY = {
  ONCE: "ONCE",
  MULTIPLE: "MULTIPLE",
};

export const ENDORSER_BLOCK = {
  FEATURED_INDIVIDUALS: "FEATURED_INDIVIDUALS",
  FEATURED_ORGANIZATIONS: "FEATURED_ORGANIZATIONS",
  INDIVIDUAL_ENDORSERS: "INDIVIDUAL_ENDORSERS",
  ORGANIZATIONAL_ENDORSERS: "ORGANIZATIONAL_ENDORSERS",
};

export const ISSUE_TYPE = {
  ITEM: "ITEM",
};

export const INTRO_LAYOUT_TYPE = {
  SINGLE: "SINGLE",
  TWO: "TWO",
  VIDEO: "VIDEO",
};

export const EMBED_VIDEO_TYPE = {
  VIMEO: "VIMEO",
  YOUTUBE: "YOUTUBE",
};

export const LANDING_POPUP_TYPES = {
  GENERAL: "GENERAL",
  DONATE: "DONATE",
  SIGNUP: "SIGNUP",
};
