name: CCRONIN CI

on:
  push:
    branches:
      - ccronin
  pull_request:
    branches:
      - ccronin
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Specify Nodejs Version
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.2'

    - name: Run Makefile
      run: make developer developer=ccronin distribution=E107TL5GSR1I7K
